[package]
name = "rlibc"
version = "0.13.0-8ed288edb"
authors = ["Ben Harris <mail@bharr.is>"]
build = "./build.sh"

[lib]
name = "rlibc"
path = "rust/src/librlibc/lib.rs"

[dependencies.core]
git = "https://github.com/bharrisau/rust-libcore.git"
